//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamalCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Student_ID { get; set; }
        public string Student_name { get; set; }
        public string Student_adress { get; set; }
        public Nullable<int> Student_age { get; set; }
        public string Student_phone { get; set; }
        public Nullable<int> Courses_ID { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
